#!/usr/bin/python

import argparse
import urllib2
import json
import DiffieHellman

# openssl dgst -sha256 -sign ~/.ssh/id_rsa f > f.sign

dh = DiffieHellman.DiffieHellman()
print(dh.publicKey)

'''
parser = argparse.ArgumentParser(description='User configuration utility')

response = urllib2.urlopen('http://localhost:8000/info')
data = json.load(response)

subparsers = parser.add_subparsers(title='commands', help='-h gives command help')

for command in data['response']:
  subparser = subparsers.add_parser(command['name'], help='Help for command')

  for option in command['options']:
    subparser.add_argument('--' + option['name'], help=option['description'])

args = parser.parse_args()
'''
