#!/usr/bin/python

import argparse
import urllib2
import json
import commands
import subprocess
import paramiko.agent
import base64
import hashlib
import os.path

home = os.path.expanduser("~")

def getCmdFromArgs(args):
  return { 'cl-command': args.__command
         , 'cl-options': [[k, v] for k, v in vars(args).items() if k != '__command' and v is not None]
         }

def getCmdString(cmd):
  return cmd['cl-command'] + ''.join(sorted([k + v for k, v in cmd['cl-options']]))

def getSignedCmd(cmd):
  cmdString = getCmdString(cmd)
  cmdHash = hashlib.sha1(cmdString).hexdigest()
  response = urllib2.urlopen('http://localhost:8000/dh', json.dumps({ 'req-hash': cmdHash }))

  svRandBlob = json.load(response)['response']
  svRand = base64.b64decode(svRandBlob)

  agent = paramiko.Agent()
  keys = agent.get_keys()

  if len(keys) < 1:
    subprocess.call('ssh-add')
    agent = paramiko.Agent()
    keys = agent.get_keys()

  pubkeySha1 = ''

  with open(home + '/.ssh/id_rsa.pub', 'r') as content_file:
    pubkey = content_file.read()
    pubkeySha1 = hashlib.sha1(pubkey).hexdigest()

  sig = base64.b64encode(keys[0].sign_ssh_data(svRand + cmdString))

  sigCmd = dict(cmd)
  sigCmd['cl-sig'] = [pubkeySha1, sig]
  return sigCmd

# Get supported commands
response = urllib2.urlopen('http://localhost:8000/info')
data = json.load(response)

commands = data['response']

# Parser configuration
parser = argparse.ArgumentParser(description='User configuration utility')

subparsers = parser.add_subparsers(title='commands', dest='__command', help='-h gives command help')

for _, command in commands:
  subparser = subparsers.add_parser(command['name'], help='Help for command')

  if 'options' in command:
    for option in command['options']:
      subparser.add_argument('--' + option['name'], help=option['description'])

args = parser.parse_args()

cmd = getCmdFromArgs(args)
cmdInfo = dict(commands)[args.__command]

if cmdInfo.get('auth', False) and args.password is None:
  cmd = getSignedCmd(cmd)

if 'ssh-key' in cmdInfo['options'] and cmd['ssh_key']:
  cmd['ssh-key'] = "asd"

response = urllib2.urlopen('http://localhost:8000/command', json.dumps(cmd))

print(json.load(response))
